#ifndef clox_common_h
#define clox_common_h

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// Enables NaN Boxing for value representation
#define NAN_BOXING

// Prints the instructions generated by the compiler for each function (including the top-level script function).
//#define DEBUG_PRINT_CODE

// Prints the stack as the interpreter runs.
//#define DEBUG_TRACE_EXECUTION

// Makes the GC runs as frequently as possible (stress test).
#define DEBUG_STRESS_GC

// Prints information to the console when some operation with dynamic memory occurs.
//#define DEBUG_LOG_GC

#endif